### ISSUE TITLE
Link to theme pdf

### ISSUE THREAD

**Issue by RaptornVts** [fsmk/consilience16#10]
Hey! The pdf I shared with you, is our sponsorship proposal, pleas take it down ASAP. Ill send you the new doc.  Also under themes, can you change the action button to " Click to view conference the

mes"   Attach this one
[Schedule-Final 7E.pdf](https://github.com/fsmk/consilience16/files/257352/Schedule-Final.7E.pdf)

**Comment by adityasaky** [comment]
To be clear, replace the current pdf linked with the one above?

**Comment by RaptornVts** [comment]
Yes, that's right.

Sent from Yahoo Mail on Android 

  On Tue, 10 May, 2016 at 22:34, Aditya Sakynotifications@github.com wrote:  
To be clear, replace the current pdf linked with the one above?

**Comment by adityasaky** [comment]
Changed.
