### ISSUE TITLE
New Sponsor

### ISSUE THREAD

**Issue by RaptornVts** [fsmk/consilience16#11]
Hey! Please add another to our sponsors. Obhan & Associates, Ive attached their logo and description 

![o a firm logo](https://cloud.githubusercontent.com/assets/19243443/15154993/18c110a0-16fe-11e6-809d-47a3f430f904.jpg)
[O&A LOGO (high resolution).pdf](https://github.com/fsmk/consilience16/files/257699/O.A.LOGO.high.resolution.pdf)

 Obhan & Associates offers end to end services in the fields of intellectual property law and corporate law with the goal of aiding and assisting its clients at every stage, and is recognised as one of India’s leading firms.

**Comment by adityasaky** [comment]
Added.

**Comment by RaptornVts** [comment]
Thanks!

Sent from Yahoo Mail on Android 

  On Tue, 10 May, 2016 at 23:03, Aditya Sakynotifications@github.com wrote:  
Added.
