### ISSUE TITLE
Minor addition

### ISSUE THREAD

**Issue by RaptornVts** [fsmk/consilience16#12]
Hey! On the landing page, between the image banner and the about portion, can we write " Supported by the MHRD Chair in IP, NLS". Also ive attached some more high res images of the NLS campus, see which ones are most suitable for the landing page, and change as you see best. Thank you for all your help. Im sorry for so many requests, our funding partners are being very meticulous. 
![img_7202](https://cloud.githubusercontent.com/assets/19243443/15156215/a5b82e76-1703-11e6-87b4-c278129e03b0.JPG)
![img_7221](https://cloud.githubusercontent.com/assets/19243443/15156220/a6a3f838-1703-11e6-951f-f2085edcc604.JPG)
![img_7233](https://cloud.githubusercontent.com/assets/19243443/15156221/a6aea4d6-1703-11e6-8b89-b85f05a47dc6.JPG)

**Comment by adityasaky** [comment]
Added. Please check if they look okay.

**Comment by shashankmc** [comment]
Closing this issue as it is already taken care.
