### ISSUE TITLE
Some changes

### ISSUE THREAD

**Issue by RaptornVts** [fsmk/consilience16#13]
Hey! 
- There is an error in the timing for session 5, 
- we need to add a registration part where we will display registration details and prices. I will send across this info, additionally we need to add two sponsors, Ive attached their logos here. 
- We also need to add the following in the new registration part " SpicyIP and the Law and Technology Society invite you to join us for what is sure to be an absolutely fascinating event! The conference is open to the public, but attendance is subject to registration prior to the event, and a confirmation of the same from the Registration Desk. Registration costs for attending the whole event over the two days are as follows:

Corporates: Rs. 5000
Non-profits: Rs. 3000
Students: Rs 1000
Other individuals: Rs 2500
The Gala Dinner on the first day is sponsored by the Texas A&M University. To register, please send an email stating your name, designation and institutional affiliation to ltech.nls@gmail.comwith subject “Registration for Consilience”.

Our special thanks go out, of course, to our Sponsors: Obhan and Associates, Software Freedom Law Centre, and the Indian Cellular Association. "
- Additionally
  ![indian-cellular-association-thumb](https://cloud.githubusercontent.com/assets/19243443/15220792/67eda7e0-1886-11e6-82e6-3302f513b652.jpg)
  ![tam-primarymarkb](https://cloud.githubusercontent.com/assets/19243443/15220793/67f238fa-1886-11e6-9d9f-cf52d0fc9212.png)
  
  in the themes section, write this as the description and have the link to the doc as well. 

"To set the stage for the rest of the event, we will be kicking things off at a high note with a Keynote Address from the phenomenal Professor Richard Jefferson, the pioneer behind Biological Open Source, The Lens, and Cambia! Currently a Professor of Biological Innovation at the Queensland University of Technology, Professor Jefferson was named as one of the world’s 50 most influential technologists in 2003 by the Scientific American.

The theme for this year’s Consilience is Open Sesame: Unlocking IP to Unleash the Commons. The term ‘Open Access’ has become part of the IP vocabulary thanks to a powerful campaign in the last few decades,  and today finds resonance in a cornucopia of sectors, ranging from educational content (Khan Academy) to Biotechnology (BiOS) to Artificial Intelligence research (Theano). Traditionally, Open Access debates have focused on two core issues: Access to Knowledge/Goods at affordable prices (A2K), and Closed versus Open Creative Processes.

At Consilience 2016, however, we plan to kick things up a notch. We will be exploring not only Open Access as an IP regime in-and-of itself, but also venturing into new areas such as Open Access within IP regimes and the multiple facets of transparency, and the Developing Country Dimension. As our readers will know, these are topics very close to the heart of the work SpicyIP has done over its decade of existence, and what better way to celebrate our Anniversary than to highlight and delve into these issues in a new light with some of the best minds in the IP field!

The two sessions will focus on the developing country perspective and fostering open access within IP Regimes respectively "

Regards,

Mohnish Mathew.

**Comment by shashankmc** [comment]
Added.
