### ISSUE TITLE
Add a sponsor

### ISSUE THREAD

**Issue by RaptornVts** [fsmk/consilience16#14]
Hey! We need to add the Indian Journal of Law and Technology as a sponsor as well. This is their description, 
"The Indian Journal of Law and Technology (IJLT) is a student-edited, peer-reviewed, open access law journal published annually by the National Law School of India University, Bangalore. IJLT is the first and only law journal in India devoted exclusively to the study of the interface between law and technology."

**Comment by RaptornVts** [comment]
![ijlt-nlsiu](https://cloud.githubusercontent.com/assets/19243443/15254412/5106e0fe-1954-11e6-8273-e13a7632b60f.jpg)

**Comment by shashankmc** [comment]
It's added. Yet to push it to the web server. Will do it asap.
