### ISSUE TITLE
Text change in theme description

### ISSUE THREAD

**Issue by RaptornVts** [fsmk/consilience16#15]
Hey! This has to be added in the theme section at the end
"
**Developing country perspective**:
 Most discussions around IP and open access revolve around “developed countries” and their specific socio-economic context. To this extent, the frame
fails to account for developing countries and their concerns. Illustratively, while
developed countries take “bandwidth” for granted, developing countries may
face serious issues on this front, preventing them from meaningful participation in
the open access movement (which largely relies on content publication/
dissemination via the internet).
This conference will therefore bring some attention to the developing country
dimension and deliberate on the current frame and how it might need to be
adapted and/or overhauled.

**Fostering openness within IP Regimes:** 
The classic IP vs Open Access frame is predicated on the notion that IP regimes are inherently “closed”. While this may hold true (to a significant extent), it fails to account for the potential openness in IP regimes. In other words, IP regimes
could be pried open to foster greater levels of openness and transparency.

One could even argue that openness lies at the heart of IP regimes; for it is the
sine qua non for the grant of the right in the first place. Illustratively, patents are
to be compulsorily disclosed and published, should the applicant desire a twenty- year monopoly protection. Such disclosure is meant to aid the public in accessing
and working the patented invention, and learning from it in the process. And yet,
not many have focused on this important disclosure function of patents.
"

**Comment by shashankmc** [comment]
The content is added. Yet to push it to the web server. I'm unable to do it for some reason. Will be pushing it asap.
