### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by RaptornVts** [fsmk/consilience16#3]
Hey! Can we rezise the images to make them a little taller? I'd suggest briding the gap between the images and the text.

**Comment by Kv-world** [comment]
You mean the slider image or the sponsor image?

**Comment by RaptornVts** [comment]
Sponsor image for spicyIP 

Sent from Yahoo Mail on Android 

  On Sun, 8 May, 2016 at 14:05, kingvermanotifications@github.com wrote:  
You mean the slider image or the sponsor image?

**Comment by shashankmc** [comment]
This is done.
