### ISSUE TITLE
About

### ISSUE THREAD

**Issue by RaptornVts** [fsmk/consilience16#4]
We need to add an about for Ltech NLSIU and SPicyIP

**Comment by abhi12ravi** [comment]
Can you please give me the content for this and where they have to go on the page?

**Comment by RaptornVts** [comment]
Hey, can you put the same info that you put in their sponsor description? I'll write it for l-tech. Can you leave a placeholder for it?

Sent from Yahoo Mail on Android 

  On Sun, 8 May, 2016 at 13:43, Abhiram Ravikumarnotifications@github.com wrote:  
Can you please give me the content for this and where they have to go on the page?

**Comment by abhi12ravi** [comment]
Hi  @RaptornVts 

Can you please tell me in which section you'd like this part to go?

**Comment by RaptornVts** [comment]
Hey guys, it looks beautiful. Amazing job. Thanks for everything!

Sent from Yahoo Mail on Android 

  On Sun, 8 May, 2016 at 23:15, Abhiram Ravikumarnotifications@github.com wrote:  
Closed #4.
